# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'neurodesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NeuroUI(object):
    def setupUi(self, NeuroUI):
        NeuroUI.setObjectName("NeuroUI")
        NeuroUI.resize(401, 545)#(401, 545)
        self.BG_1 = QtWidgets.QLabel(NeuroUI)
        self.BG_1.setGeometry(QtCore.QRect(-30, -10, 991, 561))#-->-30,-10,991,561
        self.BG_1.setText("")
        self.BG_1.setPixmap(QtGui.QPixmap("C:\\Users\\likhi\\Desktop\\Neuro voice assistent\\gui themes\\Black_Template.jpg"))
        self.BG_1.setScaledContents(True)
        self.BG_1.setObjectName("BG_1")
        self.Gif_1 = QtWidgets.QLabel(NeuroUI)
        self.Gif_1.setGeometry(QtCore.QRect(0, 0, 391, 341))
        self.Gif_1.setText("")
        self.Gif_1.setPixmap(QtGui.QPixmap("C:\\Users\\likhi\\Desktop\\Neuro voice assistent\\gui themes\\Aqua.gif"))
        self.Gif_1.setScaledContents(True)
        self.Gif_1.setObjectName("Gif_1")
        self.temp = QtWidgets.QTextBrowser(NeuroUI)
        self.temp.setGeometry(QtCore.QRect(100, 480, 211, 51))
        self.temp.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.temp.setObjectName("temp")
        self.textBrowser_time = QtWidgets.QTextBrowser(NeuroUI)
        self.textBrowser_time.setGeometry(QtCore.QRect(100, 420, 211, 51))
        self.textBrowser_time.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")#-->changed
        self.textBrowser_time.setObjectName("textBrowser_time")
        self.textBrowser_listen = QtWidgets.QTextBrowser(NeuroUI)
        self.textBrowser_listen.setGeometry(QtCore.QRect(100, 360, 211, 51))
        self.textBrowser_listen.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")#-->changed
        self.textBrowser_listen.setObjectName("textBrowser_listen")
        self.pushButton_start = QtWidgets.QPushButton(NeuroUI)
        self.pushButton_start.setGeometry(QtCore.QRect(100, 300, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 255, 255);\n"  #(0, 255, 255)-->default
"border-color: rgb(255, 0, 0);")
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_exit = QtWidgets.QPushButton(NeuroUI)
        self.pushButton_exit.setGeometry(QtCore.QRect(210, 300, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"border-color: rgb(255, 21, 5);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_start_2 = QtWidgets.QPushButton(NeuroUI)
        self.pushButton_start_2.setGeometry(QtCore.QRect(20, 10, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_start_2.setFont(font)
        self.pushButton_start_2.setStyleSheet("background-color:Transparent;\n"
"background-color: rgb(0, 255, 255);\n"
"border-color: rgb(255, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_start_2.setObjectName("pushButton_start_2")
        self.pushButton_start_3 = QtWidgets.QPushButton(NeuroUI)
        self.pushButton_start_3.setGeometry(QtCore.QRect(150, 10, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_start_3.setFont(font)
        self.pushButton_start_3.setStyleSheet("background-color:Transparent;\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 255, 255);\n"
"border-color: rgb(255, 0, 0);")
        self.pushButton_start_3.setObjectName("pushButton_start_3")
        self.pushButton_start_4 = QtWidgets.QPushButton(NeuroUI)
        self.pushButton_start_4.setGeometry(QtCore.QRect(270, 10, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_start_4.setFont(font)
        self.pushButton_start_4.setStyleSheet("background-color:Transparent;\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 255, 255);\n"
"border-color: rgb(255, 0, 0);")
        self.pushButton_start_4.setObjectName("pushButton_start_4")

        self.retranslateUi(NeuroUI)
        QtCore.QMetaObject.connectSlotsByName(NeuroUI)

    def retranslateUi(self, NeuroUI):
        _translate = QtCore.QCoreApplication.translate
        NeuroUI.setWindowTitle(_translate("NeuroUI", "Neuro"))
        self.pushButton_start.setText(_translate("NeuroUI", "START"))
        self.pushButton_exit.setText(_translate("NeuroUI", "EXIT"))
        self.pushButton_start_2.setText(_translate("NeuroUI", "YOUTUBE"))
        self.pushButton_start_3.setText(_translate("NeuroUI", "GOOGLE"))
        self.pushButton_start_4.setText(_translate("NeuroUI", "VSCODE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NeuroUI = QtWidgets.QDialog()
    ui = Ui_NeuroUI()
    ui.setupUi(NeuroUI)
    NeuroUI.show()
    sys.exit(app.exec_())
